### PR TITLE
smooth-scrolling

### PR DESCRIPTION
**Pull request by VinayBagalakoti**
added smooth-scrolling to the page

### CODE REVIEW

**Comment by VinayBagalakoti** [comment]
added smooth-scrolling to the page @3kh0

**Review by 3kh0 — APPROVED** [review]
Looks good

**Comment by 3kh0** [comment]
Just so you know, this is not the most updated version of my portfolio, but thanks for helping out anyway!

**Comment by VinayBagalakoti** [comment]
@3kh0 Can u add hacktoberfest label please

**Comment by 3kh0** [comment]
@VinayBagalakoti This PR should have been accepted since the entire repo has the `hacktoberfest` tag already.

**Comment by VinayBagalakoti** [comment]
@3kh0 I think you need put hacktoberfest tag to issue 
image

**Pull request merged**
